{% set name = "sardana-icepap" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/icepap-organization/sardana-icepap/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fe8b5ced9e4fadeda1bdd3b290010383d17318731b2ccb9db5c99c5b702515b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sardana
    - icepap

test:
  imports:
    - sardana_icepap
    - sardana_icepap.ctrl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/icepap-organization/sardana-icepap
  summary: IcePAP plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
