schema_version: 1

context:
  name: sardana-icepap
  version: 4.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f3c33b922fbcedf6186e7b96586606bdbb4a8315a51a7034315d779ca19f91f9

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - sardana-core
    - pytango
    - icepap

tests:
  - python:
      imports:
        - sardana_icepap
        - sardana_icepap.ctrl
      python_version: ["${{ python_min }}.*", "3.*"]

about:
  summary: IcePAP plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/icepap-organization/sardana-icepap

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
