schema_version: 1

context:
  name: sardana-icepap
  version: "4.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: eea3287ed5c0ef5a812260b1b4b1186c129db9733b82eeb8afbe357894157bf9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - sardana-core
    - pytango
    - icepap

tests:
  - python:
      imports:
        - sardana_icepap
        - sardana_icepap.ctrl
      python_version: ["${{ python_min }}.*", "3.*"]

about:
  summary: IcePAP plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/icepap-organization/sardana-icepap

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
